#!/bin/sh

wifi="$(cat /sys/class/net/wlp3s0/operstate)"

# If wifi is up, display "Antenna Bars". Otherwise display "Satellite Antenna"
[ "$wifi" = "up" ] && env printf '\U0001F4F6' || env printf '\U0001F6F0'
