#!/bin/sh

# Retrieve the battery percentage
battery="$(cat /sys/class/power_supply/BAT0/capacity)"

case $(cat /sys/class/power_supply/BAT0/status) in
	"Full") status=$(env printf '\U000026A1') ;; # Lightning bolt emoji
	"Discharging") status=$(env printf '\U0001F50B') ;; # Battery emoji
	"Charging") status=$(env printf '\U0001F50C') ;;  # Electric plug emoji
	"Not charging") status=$(env printf '\U0001F50B') ;; # Battery emoji
	"Unknown") status=$(env printf '\U0000267B');; # Recycling symbol emoji
	*) exit 1 ;;
esac

# If the battery is less than 10 percent and not charging, display an exclamation point
# next to the battery percentage
[ "$status" = "$(env printf '\U0001F50B')" ] &&  [ "$battery" -lt "10" ] && echo "$(env printf '\U00002757')$battery%" && exit

# Display the status icon along with the battery percentage
echo "$status$battery%"

